### ISSUE TITLE
The request is not in the expected format. Check jQuery is loaded!

### ISSUE THREAD

**Issue by arifozelci** [sinanbozkus/FormHelper#13]
Merhabalar Sinan,

Öncelikle eline sağlık çok güzel bir servis geliştirmişsin. 
Ben başarılı bir şekilde kurduğumu düşünüyorum ancak "The request is not in the expected format. Check jQuery is loaded!" hatayı almaktayım, tekrar tekrar kurdum ama aynı hata sizce neden olabilir.

Teşekkürler.

**Comment by sinanbozkus** [comment]
Merhaba,

FormHelper, jQuery’e erişemediğinden bu hatayı alıyor olabilirsiniz. jQuery tanımlamasını layout içerisindeki <head> bölümüne eklemeyi deneyebilir misiniz?

**Comment by sinanbozkus** [comment]
@arifozelci Merhaba,

Sorunun çözüldü mü?

**Comment by arifozelci** [comment]
@sinanbozkus  Merhabalar,
Evet sorun çözüldü, Area içindeki ViewImports dosyasına aşağıdaki kodları eklemek yeterli oldu.

@using FormHelper
@addTagHelper *, FormHelper

İlginize Teşekkürler.
