### ISSUE TITLE
The request is not in the expected format. Check jQuery is loaded!

### ISSUE THREAD

**Issue by ocbdev** [sinanbozkus/FormHelper#14]
merhaba,

formu kontrol ederken şu hata ile karşılaşıyorum.. yeni bir sekmede "The request is not in the expected format. Check jQuery is loaded!" mesajı karşılıyor.. 

adımların hepsini gerçekleştirdim.

FormValidator'u kaldırdığımda sorunsuz kullanabiliyorum.

**Comment by sinanbozkus** [comment]
Merhaba,

FormHelper'a ait javascript kodları düzgün yüklenmediğinden bu hatayı almaktasın. Hatanın çözümü için uygulamanın layoutunda head tagleri arasında önce jquery'nin sonrada formhelper a ait javascript bundle dosyasının eklendiğinden emin olabilir misin?

Eğer bunlardan eminsen <form asp-formhelper="true" dan sonra action="" yerine asp-controller ve asp-action şeklinde form'a ait action'ı tanımlayabilir misin?
