### ISSUE TITLE
Model value not getting in JavaScript after form post method called.

### ISSUE THREAD

**Issue by Ahesanchauhan** [sinanbozkus/FormHelper#26]
After the call form post method, I return the view with the model object in view but I am not able to get the model result in my view javascript code. 

Code :   
**console.log("respone result", '@Model.Response');** 

I expect @Model.Response will be 1. it always returns 0 after the FormCallback method is called.

Please let me know what I am missing for this.

**Comment by DogukanTansuk** [comment]
@Ahesanchauhan do you still need help?

**Comment by DogukanTansuk** [comment]
This issue is closed due not the response
