### ISSUE TITLE
Toastr position TopCenter not working as expected

### ISSUE THREAD

**Issue by wanaxe** [sinanbozkus/FormHelper#30]
If `options.ToastrDefaultPosition = ToastrPosition.TopCenter`, the actual toastr position is BottomFullWidth. This is caused by a typo at line 53 & 54 in `Extensions/FormHelperExtensions.cs`:
```
                case ToastrPosition.TopCenter:
                    return "formhelper-toast-bottom-full-width";
```
Please kindly check and fix.

**Comment by DogukanTansuk** [comment]
@wanaxe Is this issue still remain after some updates? If it is please tell us, and we'll fix it.
