### ISSUE TITLE
The request is not in the expected format. Check jQuery is loaded! 

### ISSUE THREAD

**Issue by ofturhan** [sinanbozkus/FormHelper#31]
Hocam öncelikle elinize sağlık.. gerçekten de çok başarılı..
yukardaki hatayı aldım sonra sizin komutları yaptım hata giderilmedi. sonra denerken hatanın sweetalert2 den kaynaklı olduğunu gördüm. kullanmayınca formhelper düzeldi.
sweetalert2 yerine sweetalert kullandım bu kez de submit button tıklanmasıyla hem tostr hem de sweetalert aynı anda çalıştı :D

çözüm olarak bir  input u button type olarak önce swal çağırdım submit durumunda form buttonu çağırdım tabi gizlemek zorunda kaldım vs.. kendimce yollar anlayacağınız. daha kolay bir çözümünüz varsa destek olabilir misiniz? ya da bu yöntem ok mi? ilerde sweetalert2 için update olur mu?

teşekkür ederim şimdiden.

**Comment by DogukanTansuk** [comment]
@ofturhan If the issue still remains after updates, please let us know. 
(Hocam eger en son guncellemeleri aldiktan sonra da devam ediyorsa bir bakalim. Eger sorun yoksa issue kapatabiliriz.)
